#ifndef SOFT_SERIAL_CONFIG_H
#define SOFT_SERIAL_CONFIG_H

/* Soft Serial defines */
#define SOFT_SERIAL_PIN D2

#define SERIAL_FOLLOWER_BUFFER_LENGTH MATRIX_ROWS/2
#define SERIAL_LEADER_BUFFER_LENGTH 1

#endif /* SOFT_SERIAL_CONFIG_H */
